# Travis-CI Build for libadt
# see travis-ci.org for details

language: c

compiler:
  - gcc
  - clang

os:
  - linux

env:
  global:
   - SECRET_TOKEN=rPPjmuNMjbdspnrrTxqf

branches:
  only:
    - master

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install valgrind -y -qq
  - make clean

script:
  - make -e
  - make vg_tests
