# Travis-CI Build for libadt
# see travis-ci.org for details

sudo: required
dist: trusty

branches:
  only:
    - master

before_script:
  - make clean

script:
  - make
  - make tests
  - make vg_tests

after_success:
  - bash <(curl -s https://codecov.io/bash) -s build/

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - valgrind
      env: 
        - CC=gcc-4.9
        - AR=ar
        - RL=ranlib
    - compiler: clang
      addons:
        apt:
          packages:
            - clang
            - llvm
            - valgrind
      env:
        - CC=clang
        - AR=llvm-ar
        - RL=llvm-ranlib
