# Travis-CI Build for libadt
# see travis-ci.org for details

language: c

sudo: required
dist: xenial

branches:
  only:
    - master

before_script:
  - mkdir build

script:
  - cd build
  - cmake ..
  - make
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash) -v -s build/

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          packages:
            - build-essential
    - compiler: clang
      addons:
        apt:
          packages:
            - clang
            - llvm
      env:
        - CC=clang
        - AR=llvm-ar
        - RL=llvm-ranlib
