# Travis-CI Build for libadt
# see travis-ci.org for details

language: c

compiler:
  - gcc-4.9
  - clang

os:
  - linux

env:
  global:
   - SECRET_TOKEN=rPPjmuNMjbdspnrrTxqf

branches:
  only:
    - master

before_script:
  - make clean

script:
  - make
  - make tests
  - make vg_tests

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - build-essential
      - valgrind
    alternatives:
      - alternative:
        name: gcc
        link: /usr/bin/gcc
        path: /usr/bin/gcc-4.9
        priority: 50
