# Travis-CI Build for libadt
# see travis-ci.org for details

language: c

compiler:
  - gcc
  - clang

os:
  - linux

env:
  global:
   - SECRET_TOKEN=rPPjmuNMjbdspnrrTxqf

branches:
  only:
    - master

before_script:
  - make clean

script:
  - make -e

sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - build-essential
    update-alternatives:
    - install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
